### ISSUE TITLE
Use YAML frontmatter as page metadata header

### ISSUE THREAD

**Issue by skoji** [skoji/noramark#24]
Use YAML frontmatter as page header.

Current header:

```
lang: ja
title: the document title
stylesheets:css/default.css, css/specific.css, css/iphone.css:(only screen and (min-device-width : 320px) and (max-device-width : 480px))
```

Using YAML frontmatter

``` yaml

---
lang: ja
title: the document title
stylesheets:
   - css/default.css
   - css/specific.css
   - [css/iphonc.css, only screen and (min-device-width : 320px) and (max-device-width : 480px)]

---

```
